version: "3.3"
services:
  bot:
    build: .
    restart: always

  db:
    container_name: db
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

volumes:
  postgres_data:
